/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epm.frontfaces;
import com.epm.dao.PurchaseDAO;
import com.epm.dao.UsersDAO;
import com.epm.dao.impl.PurchaseDAOImpl;
import com.epm.dao.impl.UsersDAOImpl;
import com.epm.dto.Purchase;
import com.epm.dto.Users;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sanket
 */

public class UserForm extends javax.swing.JFrame {
    Users us;
    /**
     * Creates new form UserForm
     */   
    UsersDAO udao;
    PurchaseDAO pdao;
    public UserForm() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("Title.png")).getImage());        
        udao = new UsersDAOImpl();
        pdao = new PurchaseDAOImpl();
    }
    public UserForm(Users us){
        this();
        this.us = us;
        
        System.out.println(us.getName());
        labelHello.setText("Hello, "+us.getName());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();
        labelHello = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelExpenseManagement = new javax.swing.JPanel();
        panelExpenseCard = new javax.swing.JPanel();
        panelSearchExpense = new javax.swing.JPanel();
        panelDeleteManage = new javax.swing.JPanel();
        labelDescription1 = new javax.swing.JLabel();
        txtSearchCardLast4 = new javax.swing.JTextField();
        txtSearchCardType = new javax.swing.JTextField();
        txtSearchBank = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSearchCash = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSearchPurchaseAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSearchPurchaseDate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtSearchDescription = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtSearchExpenseType = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        labelUserID = new javax.swing.JLabel();
        txtSearchUserID = new javax.swing.JTextField();
        panelExpenseBtn = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdateExpense = new javax.swing.JButton();
        btnTable = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSearchPurchaseID = new javax.swing.JTextField();
        btnManageSearch = new javax.swing.JButton();
        panelSaveExpense = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelDescription = new javax.swing.JLabel();
        txtExpenseCard4 = new javax.swing.JTextField();
        txtExpenseCard = new javax.swing.JTextField();
        txtExpenseBank = new javax.swing.JTextField();
        txtExpenseCash = new javax.swing.JTextField();
        txtExpensePurchaseA = new javax.swing.JTextField();
        txtExpensePurchaseD = new javax.swing.JTextField();
        txtExpenseDesp = new javax.swing.JTextField();
        txtExpenseType = new javax.swing.JTextField();
        btnExpenseCardSave = new javax.swing.JButton();
        labelDateFormat = new javax.swing.JLabel();
        panelDeleteExpense = new javax.swing.JPanel();
        labelPurchase = new javax.swing.JLabel();
        txtDeletePurchaseId = new javax.swing.JTextField();
        btnDeleteExpense = new javax.swing.JButton();
        panelTableExpense = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePurchaseList = new javax.swing.JTable();
        panelUpdateExpense = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtUpdateCash = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtUpdatePurchaseAmount = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtUpdatePurchaseDate = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        labelDescription2 = new javax.swing.JLabel();
        txtUpdateDescription = new javax.swing.JTextField();
        txtUpdateCard4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtUpdateCardType = new javax.swing.JTextField();
        txtUpdateExpenseType = new javax.swing.JTextField();
        txtUpdateBank = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnUpdatePanel = new javax.swing.JButton();
        labelPurchaseUpdate = new javax.swing.JLabel();
        txtUpdatePurchaseID = new javax.swing.JTextField();
        PanelManageUser = new javax.swing.JPanel();
        panelManageBtn = new javax.swing.JPanel();
        btnUpdateProfile = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        panelManageCard = new javax.swing.JPanel();
        viewProfilePanel = new javax.swing.JPanel();
        viewProfileNameLabel = new javax.swing.JLabel();
        txtViewProfileLocation = new javax.swing.JTextField();
        viewProfileLocationLabel = new javax.swing.JLabel();
        txtViewProfileName = new javax.swing.JTextField();
        changePasswordPanel = new javax.swing.JPanel();
        oldpasswordLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        retypePasswordLabel = new javax.swing.JLabel();
        btnChangePass = new javax.swing.JToggleButton();
        txtOldPass = new javax.swing.JPasswordField();
        txtNewPass = new javax.swing.JPasswordField();
        txtRetypePass = new javax.swing.JPasswordField();
        updatePanel = new javax.swing.JPanel();
        locationLabel = new javax.swing.JLabel();
        txtUpdateLocation = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtUserLocation = new javax.swing.JTextField();
        btnAddUserName = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Expense Management v1.0");
        setBackground(new java.awt.Color(51, 255, 204));
        setPreferredSize(new java.awt.Dimension(950, 700));

        PanelHeader.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EPM v1.0");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanket\\Documents\\ExpenseManagement\\ExpenseManagement\\images\\logo.png")); // NOI18N

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        labelHello.setText("Hello!");

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(497, 497, 497)
                        .addGroup(PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHello))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeaderLayout.createSequentialGroup()
                        .addComponent(labelHello)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        panelExpenseCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        panelExpenseCard.setLayout(new java.awt.CardLayout());

        panelSearchExpense.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        panelDeleteManage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));

        labelDescription1.setText("Description:");

        txtSearchBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchBankActionPerformed(evt);
            }
        });

        jLabel15.setText("Card Last 4 Digit:");

        jLabel16.setText("Card Type:");

        jLabel17.setText("Bank Name:");

        jLabel18.setText("Expense Type:");

        jLabel19.setText("Cash Used:");

        jLabel20.setText("Purchase Date:");

        jLabel21.setText("Purchase Amount:");

        labelUserID.setText("User ID:");

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdateExpense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateExpense.setText("Update");
        btnUpdateExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateExpenseActionPerformed(evt);
            }
        });

        btnTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTable.setText("All Purchase");
        btnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExpenseBtnLayout = new javax.swing.GroupLayout(panelExpenseBtn);
        panelExpenseBtn.setLayout(panelExpenseBtnLayout);
        panelExpenseBtnLayout.setHorizontalGroup(
            panelExpenseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExpenseBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTable, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelExpenseBtnLayout.setVerticalGroup(
            panelExpenseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExpenseBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExpenseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Purchase ID:");

        btnManageSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnManageSearch.setText("Search");
        btnManageSearch.setPreferredSize(new java.awt.Dimension(63, 25));
        btnManageSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteManageLayout = new javax.swing.GroupLayout(panelDeleteManage);
        panelDeleteManage.setLayout(panelDeleteManageLayout);
        panelDeleteManageLayout.setHorizontalGroup(
            panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteManageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteManageLayout.createSequentialGroup()
                        .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDescription1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelUserID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDeleteManageLayout.createSequentialGroup()
                                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearchDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearchExpenseType, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearchPurchaseDate)
                                    .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtSearchBank, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSearchPurchaseAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSearchCash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(221, 221, 221))
                            .addGroup(panelDeleteManageLayout.createSequentialGroup()
                                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSearchCardLast4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearchCardType, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearchUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelDeleteManageLayout.createSequentialGroup()
                        .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelExpenseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDeleteManageLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36)
                                .addComponent(txtSearchPurchaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManageSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)))
                        .addGap(325, 325, 325))))
        );
        panelDeleteManageLayout.setVerticalGroup(
            panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteManageLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSearchPurchaseID)
                    .addComponent(btnManageSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserID)
                    .addComponent(txtSearchUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtSearchCardLast4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSearchCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtSearchBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchPurchaseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtSearchPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescription1)
                    .addGroup(panelDeleteManageLayout.createSequentialGroup()
                        .addComponent(txtSearchDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDeleteManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchExpenseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addGap(18, 18, 18)
                .addComponent(panelExpenseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout panelSearchExpenseLayout = new javax.swing.GroupLayout(panelSearchExpense);
        panelSearchExpense.setLayout(panelSearchExpenseLayout);
        panelSearchExpenseLayout.setHorizontalGroup(
            panelSearchExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDeleteManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        panelSearchExpenseLayout.setVerticalGroup(
            panelSearchExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchExpenseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelDeleteManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelExpenseCard.add(panelSearchExpense, "card4");

        panelSaveExpense.setEnabled(false);

        jLabel4.setText("Card Last 4 Digit:");

        jLabel9.setText("Card Type:");

        jLabel10.setText("Bank Name:");

        jLabel11.setText("Expense Type:");

        jLabel12.setText("Cash Used:");

        jLabel13.setText("Purchase Date:");

        jLabel14.setText("Purchase Amount:");

        labelDescription.setText("Description:");

        txtExpenseBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpenseBankActionPerformed(evt);
            }
        });

        btnExpenseCardSave.setText("Save");
        btnExpenseCardSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenseCardSaveActionPerformed(evt);
            }
        });

        labelDateFormat.setText("Format: YYYY-MM-DD");

        javax.swing.GroupLayout panelSaveExpenseLayout = new javax.swing.GroupLayout(panelSaveExpense);
        panelSaveExpense.setLayout(panelSaveExpenseLayout);
        panelSaveExpenseLayout.setHorizontalGroup(
            panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaveExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSaveExpenseLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(290, 290, 290))
                    .addGroup(panelSaveExpenseLayout.createSequentialGroup()
                        .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSaveExpenseLayout.createSequentialGroup()
                                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelSaveExpenseLayout.createSequentialGroup()
                                        .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtExpensePurchaseD, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                            .addComponent(txtExpenseCard4)
                                            .addComponent(txtExpenseCard)
                                            .addComponent(txtExpenseBank)
                                            .addComponent(txtExpenseCash)
                                            .addComponent(txtExpensePurchaseA))
                                        .addGap(18, 18, 18)
                                        .addComponent(labelDateFormat))
                                    .addComponent(txtExpenseDesp, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExpenseType, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelSaveExpenseLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(btnExpenseCardSave)))
                        .addContainerGap(340, Short.MAX_VALUE))))
        );
        panelSaveExpenseLayout.setVerticalGroup(
            panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaveExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtExpenseCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtExpenseCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtExpenseBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpenseCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpensePurchaseA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtExpensePurchaseD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDateFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescription)
                    .addComponent(txtExpenseDesp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSaveExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtExpenseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnExpenseCardSave)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        panelExpenseCard.add(panelSaveExpense, "card2");

        panelDeleteExpense.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        panelDeleteExpense.setEnabled(false);

        labelPurchase.setText("Purchase ID:");

        btnDeleteExpense.setText("Delete");
        btnDeleteExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteExpenseLayout = new javax.swing.GroupLayout(panelDeleteExpense);
        panelDeleteExpense.setLayout(panelDeleteExpenseLayout);
        panelDeleteExpenseLayout.setHorizontalGroup(
            panelDeleteExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteExpenseLayout.createSequentialGroup()
                .addGroup(panelDeleteExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteExpenseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelPurchase)
                        .addGap(18, 18, 18)
                        .addComponent(txtDeletePurchaseId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteExpenseLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnDeleteExpense)))
                .addContainerGap(621, Short.MAX_VALUE))
        );
        panelDeleteExpenseLayout.setVerticalGroup(
            panelDeleteExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeleteExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPurchase)
                    .addComponent(txtDeletePurchaseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteExpense)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        panelExpenseCard.add(panelDeleteExpense, "card3");

        panelTableExpense.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 153)));

        tablePurchaseList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        tablePurchaseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purchase ID", "User ID", "Card 4 Digit", "Card Type", "Bank Name", "Cash Used", "Purchase Amount", "Purchase Date", "Purchase Description", "Expense Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePurchaseList);

        javax.swing.GroupLayout panelTableExpenseLayout = new javax.swing.GroupLayout(panelTableExpense);
        panelTableExpense.setLayout(panelTableExpenseLayout);
        panelTableExpenseLayout.setHorizontalGroup(
            panelTableExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
            .addGroup(panelTableExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableExpenseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelTableExpenseLayout.setVerticalGroup(
            panelTableExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
            .addGroup(panelTableExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableExpenseLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelExpenseCard.add(panelTableExpense, "card5");

        panelUpdateExpense.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 255)));
        panelUpdateExpense.setEnabled(false);

        jLabel28.setText("Purchase Amount:");

        jLabel23.setText("Card Type:");

        jLabel24.setText("Bank Name:");

        jLabel25.setText("Expense Type:");

        labelDescription2.setText("Description:");

        jLabel26.setText("Cash Used:");

        txtUpdateBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateBankActionPerformed(evt);
            }
        });

        jLabel27.setText("Purchase Date:");

        jLabel22.setText("Card Last 4 Digit:");

        btnUpdatePanel.setText("Update");
        btnUpdatePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePanelActionPerformed(evt);
            }
        });

        labelPurchaseUpdate.setText("Purhcase ID:");

        javax.swing.GroupLayout panelUpdateExpenseLayout = new javax.swing.GroupLayout(panelUpdateExpense);
        panelUpdateExpense.setLayout(panelUpdateExpenseLayout);
        panelUpdateExpenseLayout.setHorizontalGroup(
            panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateExpenseLayout.createSequentialGroup()
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateExpenseLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnUpdatePanel))
                    .addGroup(panelUpdateExpenseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDescription2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelPurchaseUpdate))
                        .addGap(14, 14, 14)
                        .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUpdateDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateExpenseType, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUpdatePurchaseID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUpdatePurchaseDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(txtUpdateCard4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUpdateCardType, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUpdateBank, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUpdateCash, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUpdatePurchaseAmount, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        panelUpdateExpenseLayout.setVerticalGroup(
            panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPurchaseUpdate)
                    .addComponent(txtUpdatePurchaseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtUpdateCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtUpdateCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtUpdateBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdatePurchaseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtUpdatePurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescription2)
                    .addComponent(txtUpdateDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtUpdateExpenseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdatePanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelExpenseCard.add(panelUpdateExpense, "card6");

        javax.swing.GroupLayout panelExpenseManagementLayout = new javax.swing.GroupLayout(panelExpenseManagement);
        panelExpenseManagement.setLayout(panelExpenseManagementLayout);
        panelExpenseManagementLayout.setHorizontalGroup(
            panelExpenseManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExpenseManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelExpenseCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(140, 140, 140))
        );
        panelExpenseManagementLayout.setVerticalGroup(
            panelExpenseManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExpenseManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelExpenseCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Expense Management", panelExpenseManagement);

        btnUpdateProfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });

        btnViewProfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        btnAddUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnChangePassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelManageBtnLayout = new javax.swing.GroupLayout(panelManageBtn);
        panelManageBtn.setLayout(panelManageBtnLayout);
        panelManageBtnLayout.setHorizontalGroup(
            panelManageBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelManageBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelManageBtnLayout.setVerticalGroup(
            panelManageBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelManageCard.setLayout(new java.awt.CardLayout());

        viewProfileNameLabel.setText("Name:");

        txtViewProfileLocation.setEditable(false);

        viewProfileLocationLabel.setText("Location:");

        txtViewProfileName.setEditable(false);

        javax.swing.GroupLayout viewProfilePanelLayout = new javax.swing.GroupLayout(viewProfilePanel);
        viewProfilePanel.setLayout(viewProfilePanelLayout);
        viewProfilePanelLayout.setHorizontalGroup(
            viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewProfilePanelLayout.createSequentialGroup()
                        .addComponent(viewProfileNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtViewProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewProfilePanelLayout.createSequentialGroup()
                        .addComponent(viewProfileLocationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewProfileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(496, Short.MAX_VALUE))
        );
        viewProfilePanelLayout.setVerticalGroup(
            viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewProfileNameLabel)
                    .addComponent(txtViewProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewProfileLocationLabel)
                    .addComponent(txtViewProfileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(360, Short.MAX_VALUE))
        );

        panelManageCard.add(viewProfilePanel, "card2");

        oldpasswordLabel.setText("Old Password:");

        newPasswordLabel.setText("New Password:");

        retypePasswordLabel.setText("Retype Password:");

        btnChangePass.setText("Change");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changePasswordPanelLayout = new javax.swing.GroupLayout(changePasswordPanel);
        changePasswordPanel.setLayout(changePasswordPanelLayout);
        changePasswordPanelLayout.setHorizontalGroup(
            changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePasswordPanelLayout.createSequentialGroup()
                        .addComponent(btnChangePass)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(changePasswordPanelLayout.createSequentialGroup()
                        .addGroup(changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPasswordLabel)
                            .addComponent(oldpasswordLabel)
                            .addComponent(retypePasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOldPass, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtNewPass)
                            .addComponent(txtRetypePass))
                        .addContainerGap(452, Short.MAX_VALUE))))
        );
        changePasswordPanelLayout.setVerticalGroup(
            changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldpasswordLabel)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordLabel)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retypePasswordLabel)
                    .addComponent(txtRetypePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnChangePass)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        panelManageCard.add(changePasswordPanel, "card2");

        locationLabel.setText("New Location:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(locationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(txtUpdateLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnUpdate)))
                .addContainerGap(462, Short.MAX_VALUE))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(txtUpdateLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        panelManageCard.add(updatePanel, "card4");

        jLabel5.setText("User ID:");

        jLabel6.setText("Password:");

        jLabel7.setText("Location:");

        jLabel8.setText("Name:");

        btnAddUserName.setText("Add");
        btnAddUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAddUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUserLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddUserName)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        panelManageCard.add(addPanel, "card5");

        javax.swing.GroupLayout PanelManageUserLayout = new javax.swing.GroupLayout(PanelManageUser);
        PanelManageUser.setLayout(PanelManageUserLayout);
        PanelManageUserLayout.setHorizontalGroup(
            PanelManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelManageUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelManageCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelManageUserLayout.setVerticalGroup(
            PanelManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelManageUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelManageUserLayout.createSequentialGroup()
                        .addComponent(panelManageCard, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelManageBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage User", PanelManageUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        //  set the login form visible
        // set the UserForm false
        LoginForm lf = new LoginForm();
        this.setVisible(false);        
        lf.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:   
        
        panelManageCard.removeAll();
        panelManageCard.repaint();
        panelManageCard.revalidate();
        
        panelManageCard.add(viewProfilePanel);
        panelManageCard.repaint();
        panelManageCard.revalidate();
        
        txtViewProfileLocation.setText(us.getLocation());
        txtViewProfileName.setText(us.getName());
        
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        // TODO add your handling code here:
        //adding button panel
        panelManageCard.removeAll();
        panelManageCard.repaint();
        panelManageCard.revalidate();
        
        panelManageCard.add(updatePanel);
        panelManageCard.repaint();
        panelManageCard.revalidate();
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:    
        panelManageCard.removeAll();
        panelManageCard.repaint();
        panelManageCard.revalidate();
        
        panelManageCard.add(addPanel);
        panelManageCard.repaint();
        panelManageCard.revalidate();       
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        
        panelManageCard.removeAll();
        panelManageCard.repaint();
        panelManageCard.revalidate();
        panelManageCard.add(changePasswordPanel);
        panelManageCard.repaint();
        panelManageCard.revalidate();
        
        
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnAddUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserNameActionPerformed
        // TODO add your handling code here:       
        Users addUsers = new Users();
        addUsers.setUser_id(Integer.parseInt(txtUserID.getText().trim()));
        addUsers.setPassword(txtUserPassword.getText());
        addUsers.setLocation(txtUserLocation.getText());
        addUsers.setName(txtUserName.getText());       
        try {
            if(udao.addUser(addUsers))
            {   
                System.out.println("True addUsers");
                //System.out.println(addUsers.getUser_id()+" "+addUsers.getPassword()+" "+addUsers.getName()+" "+addUsers.getLocation());
                txtUserID.setText("");
                txtUserPassword.setText("");
                txtUserLocation.setText("");
                txtUserName.setText("");
                JOptionPane.showMessageDialog(this, "User added in database");
            }else{
                System.out.println("False addUsers");
                //System.out.println(addUsers.getUser_id()+" "+addUsers.getPassword()+" "+addUsers.getName()+" "+addUsers.getLocation());
//                txtUserID.setText("");
//                txtUserPassword.setText("");
//                txtUserLocation.setText("");
//                txtUserName.setText("");
                JOptionPane.showMessageDialog(this, "Try other entry");
        }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddUserNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        us.setLocation(txtUpdateLocation.getText());
        //us.setName(txtUpdateName.getText());
        try {            
            if(udao.updateProfile(us)){
                txtUpdateLocation.setText("");
                //txtUpdateName.setText("");
                JOptionPane.showMessageDialog(this, "User Crediantials Updated");
            }else{
                txtUpdateLocation.setText("");
                //txtUpdateName.setText("");
                JOptionPane.showMessageDialog(this, "User Crediantials NOT Updated");            
            }
            
        } catch (Exception ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        char[] Password = txtOldPass.getPassword();       
        String oldPass = new String(Password);
        Password = txtRetypePass.getPassword();
        String retypePass = new String (Password);
        Password = txtNewPass.getPassword();
        String newPass = new String (Password);
       
        if (oldPass.equals(us.getPassword())&(retypePass.equals(newPass))){
            if(udao.changePassword(us.getUser_id(), newPass)){
                txtOldPass.setText("");
                txtRetypePass.setText("");
                txtNewPass.setText("");
                JOptionPane.showMessageDialog(this, "Password Changed Successfully");
            }else{
                txtOldPass.setText("");
                txtRetypePass.setText("");
                txtNewPass.setText("");
                JOptionPane.showMessageDialog(this, "Password NOT changed"+"\nTry Again"+"\n DAO returned FALSE");                
            }
        }else{
            txtOldPass.setText("");
            txtRetypePass.setText("");
            txtNewPass.setText("");            
            JOptionPane.showMessageDialog(this, "Password Mismatch!"+"\nTry Again");            
            panelManageCard.removeAll();
            panelManageCard.repaint();
            panelManageCard.revalidate();
            panelManageCard.add(changePasswordPanel);
            panelManageCard.repaint();
            panelManageCard.revalidate();
        }   
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        panelExpenseCard.removeAll();
        panelExpenseCard.repaint();
        panelExpenseCard.revalidate();
        panelExpenseCard.add(panelDeleteExpense);
        panelExpenseCard.repaint();
        panelExpenseCard.revalidate();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        panelExpenseCard.removeAll();
        panelExpenseCard.repaint();
        panelExpenseCard.revalidate();
        panelExpenseCard.add(panelSaveExpense);
        panelExpenseCard.repaint();
        panelExpenseCard.revalidate();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateExpenseActionPerformed
        // TODO add your handling code here:
        panelExpenseCard.removeAll();
        panelExpenseCard.repaint();
        panelExpenseCard.revalidate();
        panelExpenseCard.add(panelUpdateExpense);
        panelExpenseCard.repaint();
        panelExpenseCard.revalidate();
    }//GEN-LAST:event_btnUpdateExpenseActionPerformed

    private void btnTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableActionPerformed
        // TODO add your handling code here:
        panelExpenseCard.removeAll();
        panelExpenseCard.repaint();
        panelExpenseCard.revalidate();
        panelExpenseCard.add(panelTableExpense);
        panelExpenseCard.repaint();
        panelExpenseCard.revalidate();
        
        List<Purchase> list = pdao.findAllPurchases(us.getUser_id());
        
//        System.out.println(list.size());
//        System.out.println(list.get(0));
        
        DefaultTableModel model = (DefaultTableModel) tablePurchaseList.getModel();
        Object rowData[] = new Object[10];
        for(int i = 0; i < list.size(); i++){
            rowData[0] = list.get(i).getPurchase_id();
            rowData[1] = list.get(i).getUser_id();
            rowData[2] = list.get(i).getCard_4_digit_info();
            rowData[3] = list.get(i).getCard_type();
            rowData[4] = list.get(i).getBank_name();
            rowData[5] = list.get(i).getCash_used();
            rowData[6] = list.get(i).getPurchase_amount();
            rowData[7] = list.get(i).getPurchase_date();
            rowData[8] = list.get(i).getPurchase_desc();
            rowData[9] = list.get(i).getExpense_type_id();
            model.addRow(rowData);        
        }
        
    }//GEN-LAST:event_btnTableActionPerformed

    private void txtExpenseBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpenseBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpenseBankActionPerformed

    private void btnExpenseCardSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenseCardSaveActionPerformed
        // TODO add your handling code here:
        Purchase pSave = new Purchase();
//        //purchase id will oracle sequence...
//        purchase.setUser_id( user.getUser_id());
//        purchase.setCard_4_digit_info(1207);
//        purchase.setCard_type("CC-MC");
//        purchase.setBank_name("Citi Bank");
//        purchase.setCash_used(0);
//        purchase.setPurchase_amount((float) 123.50);
//        purchase.setPurchase_date("2017-01-01");
//        purchase.setPurchase_desc("Toy for Ishaan.");
//        purchase.setExpense_type_id(10);
//        //===
//        PurchaseDAO purchasedao = new PurchaseDAOImpl();
//        boolean purchaseSaved = purchasedao.savePurchase(purchase);
//        Integer.parseInt(txtUserID.getText().trim()))
        

//us.getUser_id();
//If the user who entered the password, will enter in the purchase

        //pSave.setPurchase_id(Integer.parseInt(txtExpensePub.getText().trim()));
        //pSave.setUser_id(us.getUser_id());  
        //User ID not taken from the textfield
        
        pSave.setUser_id(us.getUser_id());  
        
        pSave.setCard_4_digit_info(Integer.parseInt(txtExpenseCard4.getText().trim()));
        pSave.setCard_type(txtExpenseCard.getText().trim());
        pSave.setBank_name(txtExpenseBank.getText().trim());
        pSave.setCash_used(Integer.parseInt(txtExpenseCash.getText().trim()));
        pSave.setPurchase_amount(Float.parseFloat(txtExpensePurchaseA.getText().trim()));
        pSave.setPurchase_date(txtExpensePurchaseD.getText());
        pSave.setPurchase_desc(txtExpenseDesp.getText());
        pSave.setExpense_type_id(Integer.parseInt(txtExpenseType.getText().trim()));
        
        if (pdao.savePurchase(pSave)){
            txtExpenseCard4.setText("");
            txtExpenseCard.setText("");
            txtExpenseBank.setText("");
            txtExpenseCash.setText("");
            txtExpensePurchaseA.setText("");
            txtExpensePurchaseD.setText("");
            txtExpenseDesp.setText("");
            txtExpenseType.setText("");
            JOptionPane.showMessageDialog(this, "Purchase Added");
            
        }else{
//            txtExpenseCard4.setText("");
//            txtExpenseCard.setText("");
//            txtExpenseBank.setText("");
//            txtExpenseCash.setText("");
//            txtExpensePurchaseA.setText("");
//            txtExpensePurchaseD.setText("");
//            txtExpenseDesp.setText("");
//            txtExpenseType.setText("");
            JOptionPane.showMessageDialog(this, "Purchase Not Added");       
        }
    }//GEN-LAST:event_btnExpenseCardSaveActionPerformed

    private void btnDeleteExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteExpenseActionPerformed
        // TODO add your handling code here:
        Integer pidDelete = Integer.parseInt(txtDeletePurchaseId.getText());
        if(pdao.deletePurchase(pidDelete)){
            JOptionPane.showMessageDialog(this, "Purchase Deleted");
        }else{
            JOptionPane.showMessageDialog(this, "Purchase not Deleted");
        }
        
    }//GEN-LAST:event_btnDeleteExpenseActionPerformed

    private void txtSearchBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchBankActionPerformed

    private void btnManageSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSearchActionPerformed
        // TODO add your handling code here:
        Integer pidSearch = Integer.parseInt(txtSearchPurchaseID.getText());
        
        Purchase pSearch = pdao.findPurchaseByID(pidSearch);
        if(pSearch.getUser_id()==0){
            JOptionPane.showMessageDialog(this, "Purchase ID doesn't exists");
        }else{
        txtSearchCardLast4.setText(Integer.toString(pSearch.getCard_4_digit_info()));
        txtSearchCardType.setText(pSearch.getCard_type());
        txtSearchBank.setText(pSearch.getBank_name());
        txtSearchCash.setText(Integer.toString(pSearch.getCash_used()));
        txtSearchPurchaseAmount.setText(Float.toString(pSearch.getPurchase_amount()));
        txtSearchPurchaseDate.setText(pSearch.getPurchase_date());
        txtSearchDescription.setText(pSearch.getPurchase_desc());
        txtSearchExpenseType.setText(Integer.toString(pSearch.getExpense_type_id()));
        txtSearchUserID.setText(Integer.toString(pSearch.getUser_id()));        
        }
    }//GEN-LAST:event_btnManageSearchActionPerformed

    private void txtUpdateBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateBankActionPerformed

    private void btnUpdatePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePanelActionPerformed
        // TODO add your handling code here:
        Purchase pUpdate = new Purchase();
        
        pUpdate.setUser_id(us.getUser_id());
        
        pUpdate.setPurchase_id(Integer.parseInt(txtUpdatePurchaseID.getText().trim()));
        pUpdate.setCard_4_digit_info(Integer.parseInt(txtUpdateCard4.getText().trim()));
        pUpdate.setCard_type(txtUpdateCardType.getText().trim());
        pUpdate.setBank_name(txtUpdateBank.getText().trim());
        pUpdate.setCash_used(Integer.parseInt(txtUpdateCash.getText().trim()));
        pUpdate.setPurchase_amount(Float.parseFloat(txtUpdatePurchaseAmount.getText().trim()));
        pUpdate.setPurchase_date(txtUpdatePurchaseDate.getText());
        pUpdate.setPurchase_desc(txtUpdateDescription.getText());
        pUpdate.setExpense_type_id(Integer.parseInt(txtUpdateExpenseType.getText().trim()));
        
        if(pdao.updatePurchase(pUpdate)){
            JOptionPane.showMessageDialog(this, "Purchase ID Update");
        }else{
            JOptionPane.showMessageDialog(this, "Purchase ID not Update");
        }
    }//GEN-LAST:event_btnUpdatePanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelManageUser;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAddUserName;
    private javax.swing.JToggleButton btnChangePass;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteExpense;
    private javax.swing.JButton btnExpenseCardSave;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageSearch;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTable;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateExpense;
    private javax.swing.JButton btnUpdatePanel;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JPanel changePasswordPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelDateFormat;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelDescription1;
    private javax.swing.JLabel labelDescription2;
    private javax.swing.JLabel labelHello;
    private javax.swing.JLabel labelPurchase;
    private javax.swing.JLabel labelPurchaseUpdate;
    private javax.swing.JLabel labelUserID;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel oldpasswordLabel;
    private javax.swing.JPanel panelDeleteExpense;
    private javax.swing.JPanel panelDeleteManage;
    private javax.swing.JPanel panelExpenseBtn;
    private javax.swing.JPanel panelExpenseCard;
    private javax.swing.JPanel panelExpenseManagement;
    private javax.swing.JPanel panelManageBtn;
    private javax.swing.JPanel panelManageCard;
    private javax.swing.JPanel panelSaveExpense;
    private javax.swing.JPanel panelSearchExpense;
    private javax.swing.JPanel panelTableExpense;
    private javax.swing.JPanel panelUpdateExpense;
    private javax.swing.JLabel retypePasswordLabel;
    private javax.swing.JTable tablePurchaseList;
    private javax.swing.JTextField txtDeletePurchaseId;
    private javax.swing.JTextField txtExpenseBank;
    private javax.swing.JTextField txtExpenseCard;
    private javax.swing.JTextField txtExpenseCard4;
    private javax.swing.JTextField txtExpenseCash;
    private javax.swing.JTextField txtExpenseDesp;
    private javax.swing.JTextField txtExpensePurchaseA;
    private javax.swing.JTextField txtExpensePurchaseD;
    private javax.swing.JTextField txtExpenseType;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtOldPass;
    private javax.swing.JPasswordField txtRetypePass;
    private javax.swing.JTextField txtSearchBank;
    private javax.swing.JTextField txtSearchCardLast4;
    private javax.swing.JTextField txtSearchCardType;
    private javax.swing.JTextField txtSearchCash;
    private javax.swing.JTextField txtSearchDescription;
    private javax.swing.JTextField txtSearchExpenseType;
    private javax.swing.JTextField txtSearchPurchaseAmount;
    private javax.swing.JTextField txtSearchPurchaseDate;
    private javax.swing.JTextField txtSearchPurchaseID;
    private javax.swing.JTextField txtSearchUserID;
    private javax.swing.JTextField txtUpdateBank;
    private javax.swing.JTextField txtUpdateCard4;
    private javax.swing.JTextField txtUpdateCardType;
    private javax.swing.JTextField txtUpdateCash;
    private javax.swing.JTextField txtUpdateDescription;
    private javax.swing.JTextField txtUpdateExpenseType;
    private javax.swing.JTextField txtUpdateLocation;
    private javax.swing.JTextField txtUpdatePurchaseAmount;
    private javax.swing.JTextField txtUpdatePurchaseDate;
    private javax.swing.JTextField txtUpdatePurchaseID;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserLocation;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserPassword;
    private javax.swing.JTextField txtViewProfileLocation;
    private javax.swing.JTextField txtViewProfileName;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JLabel viewProfileLocationLabel;
    private javax.swing.JLabel viewProfileNameLabel;
    private javax.swing.JPanel viewProfilePanel;
    // End of variables declaration//GEN-END:variables
}
